- dify/dify-support/dify-support-workflow/src/main/java/io/github/guoshiqiufeng/dify/workflow/dto/response/WorkflowLogs.java
- docs/en/guide/feature/workflow.md
- docs/guide/feature/workflow.md
> fix: WorkflowLogs filed createdAt Type error

- dify/dify-support/dify-support-chat/src/main/java/io/github/guoshiqiufeng/dify/chat/impl/DifyChatDefaultImpl.java
- dify/dify-support/dify-support-workflow/src/main/java/io/github/guoshiqiufeng/dify/workflow/impl/DifyWorkflowDefaultImpl.java
> fix: file type error

- dify/dify-support/dify-support-chat/src/main/java/io/github/guoshiqiufeng/dify/chat/impl/DifyChatDefaultImpl.java
- dify/dify-support/dify-support-dataset/src/main/java/io/github/guoshiqiufeng/dify/dataset/constant/DatasetUriConstant.java
- dify/dify-support/dify-support-dataset/src/main/java/io/github/guoshiqiufeng/dify/dataset/impl/DifyDatasetDefaultImpl.java
- dify/dify-support/dify-support-workflow/src/main/java/io/github/guoshiqiufeng/dify/workflow/impl/DifyWorkflowDefaultImpl.java
> feat: url replacement optimization

- .github/workflows/gradle-dify-test.yml
- .gitignore
- dify/dify-support/dify-support-server/build.gradle
- dify/dify-support/dify-support-server/src/main/java/io/github/guoshiqiufeng/dify/server/DifyServer.java
- dify/dify-support/dify-support-server/src/main/java/io/github/guoshiqiufeng/dify/server/dto/response/ApiKeyResponseVO.java
- dify/dify-support/dify-support-server/src/main/java/io/github/guoshiqiufeng/dify/server/dto/response/AppsResponseVO.java
- dify/dify-support/dify-support-server/src/main/java/io/github/guoshiqiufeng/dify/server/impl/DifyServerRedisImpl.java
- dify/spring-boot-starter/dify-spring-boot-starter/build.gradle
- dify/spring-boot-starter/dify-spring-boot-starter/src/test/java/io/github/guoshiqiufeng/dify/boot/ServerTest.java
- docs/en/guide/feature/server.md
- docs/en/guide/introduction.md
- docs/guide/feature/server.md
- docs/guide/introduction.md
> feat: server api

- .github/workflows/docs-build.yml
- .github/workflows/gradle-build.yml
- .github/workflows/gradle-dify-test.yml
- dify/dify-support/dify-support-dataset/src/main/java/io/github/guoshiqiufeng/dify/dataset/DifyDataset.java
- dify/dify-support/dify-support-dataset/src/main/java/io/github/guoshiqiufeng/dify/dataset/client/DifyDatasetClient.java
- dify/dify-support/dify-support-dataset/src/main/java/io/github/guoshiqiufeng/dify/dataset/constant/DatasetUriConstant.java
- dify/dify-support/dify-support-dataset/src/main/java/io/github/guoshiqiufeng/dify/dataset/dto/response/TextEmbeddingListResponse.java
- dify/dify-support/dify-support-dataset/src/main/java/io/github/guoshiqiufeng/dify/dataset/dto/response/textembedding/TextEmbedding.java
- dify/dify-support/dify-support-dataset/src/main/java/io/github/guoshiqiufeng/dify/dataset/dto/response/textembedding/TextEmbeddingIcon.java
- dify/dify-support/dify-support-dataset/src/main/java/io/github/guoshiqiufeng/dify/dataset/dto/response/textembedding/TextEmbeddingLabel.java
- dify/dify-support/dify-support-dataset/src/main/java/io/github/guoshiqiufeng/dify/dataset/dto/response/textembedding/TextEmbeddingModel.java
- dify/dify-support/dify-support-dataset/src/main/java/io/github/guoshiqiufeng/dify/dataset/dto/response/textembedding/TextEmbeddingModelProperties.java
- dify/dify-support/dify-support-dataset/src/main/java/io/github/guoshiqiufeng/dify/dataset/enums/ModelFeatureEnum.java
- dify/dify-support/dify-support-dataset/src/main/java/io/github/guoshiqiufeng/dify/dataset/enums/ModelStatusEnum.java
- dify/dify-support/dify-support-dataset/src/main/java/io/github/guoshiqiufeng/dify/dataset/impl/DifyDatasetClientImpl.java
- dify/dify-support/dify-support-dataset/src/main/java/io/github/guoshiqiufeng/dify/dataset/impl/DifyDatasetDefaultImpl.java
- dify/spring-boot-starter/dify-spring-boot-starter/src/test/java/io/github/guoshiqiufeng/dify/boot/DatasetTest.java
- docs/en/guide/feature/dataset.md
- docs/guide/feature/dataset.md
> [!Tip]
>
Resolves #47 
change.
> feat: Get available embedding models

- .github/workflows/gradle-publish.yml
- bom/build.gradle
- build.gradle
- dify/build.gradle
- dify/dify-support/build.gradle
- dify/spring-boot-starter/build.gradle
- settings.gradle
> [!Tip]
>
Resolves #49 
change.
> feat: Change Central Warehouse

- dify/dify-support/dify-support-dataset/src/main/java/io/github/guoshiqiufeng/dify/dataset/client/DifyDatasetClient.java
- dify/dify-support/dify-support-dataset/src/main/java/io/github/guoshiqiufeng/dify/dataset/dto/request/DocumentCreateByFileRequest.java
- dify/dify-support/dify-support-dataset/src/main/java/io/github/guoshiqiufeng/dify/dataset/dto/request/DocumentCreateByTextRequest.java
- dify/dify-support/dify-support-dataset/src/main/java/io/github/guoshiqiufeng/dify/dataset/dto/request/DocumentMetaDataUpdateRequest.java
- dify/dify-support/dify-support-dataset/src/main/java/io/github/guoshiqiufeng/dify/dataset/dto/request/DocumentUpdateByFileRequest.java
- dify/dify-support/dify-support-dataset/src/main/java/io/github/guoshiqiufeng/dify/dataset/dto/request/DocumentUpdateByTextRequest.java
- dify/dify-support/dify-support-dataset/src/main/java/io/github/guoshiqiufeng/dify/dataset/dto/request/MetaDataCreateRequest.java
- dify/dify-support/dify-support-dataset/src/main/java/io/github/guoshiqiufeng/dify/dataset/dto/request/MetaDataUpdateRequest.java
- dify/dify-support/dify-support-dataset/src/main/java/io/github/guoshiqiufeng/dify/dataset/dto/request/RetrieveRequest.java
- dify/dify-support/dify-support-dataset/src/main/java/io/github/guoshiqiufeng/dify/dataset/dto/request/SegmentChildChunkCreateRequest.java
- dify/dify-support/dify-support-dataset/src/main/java/io/github/guoshiqiufeng/dify/dataset/dto/request/SegmentChildChunkDeleteRequest.java
- dify/dify-support/dify-support-dataset/src/main/java/io/github/guoshiqiufeng/dify/dataset/dto/request/SegmentChildChunkPageRequest.java
- dify/dify-support/dify-support-dataset/src/main/java/io/github/guoshiqiufeng/dify/dataset/dto/request/SegmentChildChunkUpdateRequest.java
- dify/dify-support/dify-support-dataset/src/main/java/io/github/guoshiqiufeng/dify/dataset/dto/request/SegmentCreateRequest.java
- dify/dify-support/dify-support-dataset/src/main/java/io/github/guoshiqiufeng/dify/dataset/dto/request/SegmentPageRequest.java
- dify/dify-support/dify-support-dataset/src/main/java/io/github/guoshiqiufeng/dify/dataset/dto/request/SegmentUpdateRequest.java
> fix: feign vo use

- dify/dify-support/dify-support-chat/src/main/java/io/github/guoshiqiufeng/dify/chat/DifyChat.java
- dify/dify-support/dify-support-chat/src/main/java/io/github/guoshiqiufeng/dify/chat/client/DifyChatClient.java
- dify/dify-support/dify-support-chat/src/main/java/io/github/guoshiqiufeng/dify/chat/dto/response/ChatMessageSendCompletionResponse.java
- dify/dify-support/dify-support-chat/src/main/java/io/github/guoshiqiufeng/dify/chat/dto/response/jackson/CompletionDataDeserializer.java
- dify/dify-support/dify-support-chat/src/main/java/io/github/guoshiqiufeng/dify/chat/dto/response/message/CompletionData.java
- dify/dify-support/dify-support-chat/src/main/java/io/github/guoshiqiufeng/dify/chat/dto/response/message/NodeFinishedData.java
- dify/dify-support/dify-support-chat/src/main/java/io/github/guoshiqiufeng/dify/chat/dto/response/message/NodeStartedData.java
- dify/dify-support/dify-support-chat/src/main/java/io/github/guoshiqiufeng/dify/chat/dto/response/message/WorkflowFinishedData.java
- dify/dify-support/dify-support-chat/src/main/java/io/github/guoshiqiufeng/dify/chat/dto/response/message/WorkflowStartedData.java
- dify/dify-support/dify-support-chat/src/main/java/io/github/guoshiqiufeng/dify/chat/enums/StreamEventEnum.java
- dify/dify-support/dify-support-chat/src/main/java/io/github/guoshiqiufeng/dify/chat/impl/DifyChatClientImpl.java
- dify/dify-support/dify-support-chat/src/main/java/io/github/guoshiqiufeng/dify/chat/impl/DifyChatDefaultImpl.java
- dify/spring-boot-starter/dify-spring-boot-starter/src/test/java/io/github/guoshiqiufeng/dify/boot/ChatTest.java
- gradle.properties
> fix: chat completion

- README-zh.md
- README.md
- dify/spring-boot-starter/dify-spring-boot-starter-autoconfigure/src/main/java/io/github/guoshiqiufeng/dify/autoconfigure/DifyServerAutoConfiguration.java
- dify/spring-boot-starter/dify-spring-boot-starter-autoconfigure/src/main/java/io/github/guoshiqiufeng/dify/autoconfigure/DifyServerRedisTokenAutoConfiguration.java
- dify/spring-boot-starter/dify-spring-boot-starter-autoconfigure/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
- gradle.properties
> fix: server token redis

- README-zh.md
- README.md
- dify/dify-core/src/main/java/io/github/guoshiqiufeng/dify/core/config/DifyProperties.java
- gradle.properties
> fix: empty config

- dify/dify-client/dify-client-spring5/src/main/java/io/github/guoshiqiufeng/dify/client/spring5/dataset/DifyDatasetDefaultClient.java
- dify/dify-client/dify-client-spring5/src/main/java/io/github/guoshiqiufeng/dify/client/spring5/utils/DatasetHeaderUtils.java
- dify/dify-client/dify-client-spring6/src/main/java/io/github/guoshiqiufeng/dify/client/spring6/dataset/DifyDatasetDefaultClient.java
- dify/dify-client/dify-client-spring6/src/main/java/io/github/guoshiqiufeng/dify/client/spring6/utils/DatasetHeaderUtils.java
- dify/dify-support/dify-support-dataset/src/main/java/io/github/guoshiqiufeng/dify/dataset/DifyDataset.java
- dify/dify-support/dify-support-dataset/src/main/java/io/github/guoshiqiufeng/dify/dataset/client/DifyDatasetClient.java
- dify/dify-support/dify-support-dataset/src/main/java/io/github/guoshiqiufeng/dify/dataset/dto/request/BaseDatasetRequest.java
- dify/dify-support/dify-support-dataset/src/main/java/io/github/guoshiqiufeng/dify/dataset/impl/DifyDatasetClientImpl.java
> [!Tip]
>
Resolves #65 
change.
> feat: Add back the apikey in the dataset request

- README-zh.md
- README.md
- dify/dify-client/dify-client-spring5/build.gradle
- dify/dify-client/dify-client-spring5/src/main/java/io/github/guoshiqiufeng/dify/client/spring5/builder/BaseDifyBuilder.java
- dify/dify-client/dify-client-spring5/src/main/java/io/github/guoshiqiufeng/dify/client/spring5/builder/DifyChatBuilder.java
- dify/dify-client/dify-client-spring5/src/main/java/io/github/guoshiqiufeng/dify/client/spring5/builder/DifyDatasetBuilder.java
- dify/dify-client/dify-client-spring5/src/main/java/io/github/guoshiqiufeng/dify/client/spring5/builder/DifyServerBuilder.java
- dify/dify-client/dify-client-spring5/src/main/java/io/github/guoshiqiufeng/dify/client/spring5/builder/DifyWorkflowBuilder.java
- dify/dify-client/dify-client-spring5/src/test/java/io/github/guoshiqiufeng/dify/client/spring5/builder/BaseDifyBuilderTest.java
- dify/dify-client/dify-client-spring5/src/test/java/io/github/guoshiqiufeng/dify/client/spring5/builder/DifyChatBuilderTest.java
- dify/dify-client/dify-client-spring5/src/test/java/io/github/guoshiqiufeng/dify/client/spring5/builder/DifyDatasetBuilderTest.java
- dify/dify-client/dify-client-spring5/src/test/java/io/github/guoshiqiufeng/dify/client/spring5/builder/DifyServerBuilderTest.java
- dify/dify-client/dify-client-spring5/src/test/java/io/github/guoshiqiufeng/dify/client/spring5/builder/DifyWorkflowBuilderTest.java
- dify/dify-client/dify-client-spring6/build.gradle
- dify/dify-client/dify-client-spring6/src/main/java/io/github/guoshiqiufeng/dify/client/spring6/builder/BaseDifyBuilder.java
- dify/dify-client/dify-client-spring6/src/main/java/io/github/guoshiqiufeng/dify/client/spring6/builder/DifyChatBuilder.java
- dify/dify-client/dify-client-spring6/src/main/java/io/github/guoshiqiufeng/dify/client/spring6/builder/DifyDatasetBuilder.java
- dify/dify-client/dify-client-spring6/src/main/java/io/github/guoshiqiufeng/dify/client/spring6/builder/DifyServerBuilder.java
- dify/dify-client/dify-client-spring6/src/main/java/io/github/guoshiqiufeng/dify/client/spring6/builder/DifyWorkflowBuilder.java
- dify/dify-client/dify-client-spring6/src/test/java/io/github/guoshiqiufeng/dify/client/spring6/builder/BaseDifyBuilderTest.java
- dify/dify-client/dify-client-spring6/src/test/java/io/github/guoshiqiufeng/dify/client/spring6/builder/DifyChatBuilderTest.java
- dify/dify-client/dify-client-spring6/src/test/java/io/github/guoshiqiufeng/dify/client/spring6/builder/DifyDatasetBuilderTest.java
- dify/dify-client/dify-client-spring6/src/test/java/io/github/guoshiqiufeng/dify/client/spring6/builder/DifyServerBuilderTest.java
- dify/dify-client/dify-client-spring6/src/test/java/io/github/guoshiqiufeng/dify/client/spring6/builder/DifyWorkflowBuilderTest.java
- dify/dify-core/src/main/java/io/github/guoshiqiufeng/dify/core/client/BaseDifyClient.java
- docs/en/guide/builder.md
- docs/guide/builder.md
> [!Tip]
>
Resolves #68 
change.
> feat: client builder

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- .devcontainer/scripts/onCreateCommand.sh
> feat: devcontainer init

- docs/.vuepress/config.js
> doc: update builder link

- build.gradle
- settings.gradle
> fix: update gradle repositories

- .github/workflows/gradle-dify-test.yml
- build.gradle
- dify/dify-client/dify-client-spring5/build.gradle
- dify/dify-client/dify-client-spring5/src/test/java/io/github/guoshiqiufeng/dify/client/spring5/base/BaseDifyDefaultClientTest.java
- dify/dify-client/dify-client-spring5/src/test/java/io/github/guoshiqiufeng/dify/client/spring5/utils/DatasetHeaderUtilsTest.java
- dify/dify-client/dify-client-spring5/src/test/java/io/github/guoshiqiufeng/dify/client/spring5/utils/DifyExchangeStrategiesTest.java
- dify/dify-client/dify-client-spring5/src/test/java/io/github/guoshiqiufeng/dify/client/spring5/utils/MultipartInputStreamFileResourceTest.java
- dify/dify-client/dify-client-spring5/src/test/java/io/github/guoshiqiufeng/dify/client/spring5/utils/WebClientUtilTest.java
- dify/dify-client/dify-client-spring6/build.gradle
- dify/dify-client/dify-client-spring6/src/test/java/io/github/guoshiqiufeng/dify/client/spring6/base/BaseDifyDefaultClientTest.java
- dify/dify-client/dify-client-spring6/src/test/java/io/github/guoshiqiufeng/dify/client/spring6/chat/DifyChatDefaultClientTest.java
- dify/dify-client/dify-client-spring6/src/test/java/io/github/guoshiqiufeng/dify/client/spring6/dataset/DifyDatasetDefaultClientTest.java
- dify/dify-client/dify-client-spring6/src/test/java/io/github/guoshiqiufeng/dify/client/spring6/server/DifyServerDefaultClientTest.java
- dify/dify-client/dify-client-spring6/src/test/java/io/github/guoshiqiufeng/dify/client/spring6/utils/DatasetHeaderUtilsTest.java
- dify/dify-client/dify-client-spring6/src/test/java/io/github/guoshiqiufeng/dify/client/spring6/utils/DifyExchangeStrategiesTest.java
- dify/dify-client/dify-client-spring6/src/test/java/io/github/guoshiqiufeng/dify/client/spring6/utils/DifyMessageConvertersTest.java
- dify/dify-client/dify-client-spring6/src/test/java/io/github/guoshiqiufeng/dify/client/spring6/utils/MultipartInputStreamFileResourceTest.java
- dify/dify-client/dify-client-spring6/src/test/java/io/github/guoshiqiufeng/dify/client/spring6/utils/WebClientUtilTest.java
- dify/dify-client/dify-client-spring6/src/test/java/io/github/guoshiqiufeng/dify/client/spring6/workflow/DifyWorkflowDefaultClientTest.java
Resolves #80 
> [!Tip]
>
change.
> feat: jacoco

- codecov.yml
- dify/dify-client/dify-client-spring5/src/main/java/io/github/guoshiqiufeng/dify/client/spring5/chat/DifyChatDefaultClient.java
- dify/dify-client/dify-client-spring5/src/test/java/io/github/guoshiqiufeng/dify/client/spring5/chat/DifyChatDefaultClientTest.java
- dify/dify-client/dify-client-spring6/src/main/java/io/github/guoshiqiufeng/dify/client/spring6/chat/DifyChatDefaultClient.java
- dify/dify-client/dify-client-spring6/src/test/java/io/github/guoshiqiufeng/dify/client/spring6/chat/DifyChatDefaultClientTest.java
- dify/dify-support/dify-support-chat/src/main/java/io/github/guoshiqiufeng/dify/chat/DifyChat.java
- dify/dify-support/dify-support-chat/src/main/java/io/github/guoshiqiufeng/dify/chat/client/DifyChatClient.java
- dify/dify-support/dify-support-chat/src/main/java/io/github/guoshiqiufeng/dify/chat/dto/request/FileUploadRequest.java
- dify/dify-support/dify-support-chat/src/main/java/io/github/guoshiqiufeng/dify/chat/dto/response/FileUploadResponse.java
- dify/dify-support/dify-support-chat/src/main/java/io/github/guoshiqiufeng/dify/chat/impl/DifyChatClientImpl.java
- dify/dify-support/dify-support-chat/src/test/java/io/github/guoshiqiufeng/dify/chat/client/DifyChatClientTest.java
- dify/dify-support/dify-support-chat/src/test/java/io/github/guoshiqiufeng/dify/chat/impl/DifyChatClientImplTest.java
- dify/dify-support/dify-support-dataset/src/main/java/io/github/guoshiqiufeng/dify/dataset/constant/DatasetUriConstant.java
- dify/spring-boot-starter/dify-spring-boot-starter/src/test/java/io/github/guoshiqiufeng/dify/boot/ChatTest.java
- dify/spring-boot-starter/dify-spring-boot-starter/src/test/java/io/github/guoshiqiufeng/dify/boot/DatasetTest.java
- dify/spring-boot2-starter/dify-spring-boot2-starter/src/test/java/io/github/guoshiqiufeng/dify/boot/ChatTest.java
- dify/spring-boot2-starter/dify-spring-boot2-starter/src/test/java/io/github/guoshiqiufeng/dify/boot/DatasetTest.java
- docs/en/guide/feature/chat.md
- docs/en/guide/introduction.md
- docs/guide/feature/chat.md
- docs/guide/introduction.md
Resolves #87 
> [!Tip]
>
change.
> feat: chat api

- dify/dify-client/dify-client-spring5/src/main/java/io/github/guoshiqiufeng/dify/client/spring5/base/BaseDifyDefaultClient.java
- dify/dify-client/dify-client-spring5/src/main/java/io/github/guoshiqiufeng/dify/client/spring5/chat/DifyChatDefaultClient.java
- dify/dify-client/dify-client-spring5/src/test/java/io/github/guoshiqiufeng/dify/client/spring5/BaseClientTest.java
- dify/dify-client/dify-client-spring5/src/test/java/io/github/guoshiqiufeng/dify/client/spring5/chat/DifyChatDefaultClientTest.java
- dify/dify-client/dify-client-spring6/src/main/java/io/github/guoshiqiufeng/dify/client/spring6/chat/DifyChatDefaultClient.java
- dify/dify-client/dify-client-spring6/src/test/java/io/github/guoshiqiufeng/dify/client/spring6/chat/DifyChatDefaultClientTest.java
- dify/dify-support/dify-support-chat/src/main/java/io/github/guoshiqiufeng/dify/chat/DifyChat.java
- dify/dify-support/dify-support-chat/src/main/java/io/github/guoshiqiufeng/dify/chat/client/DifyChatClient.java
- dify/dify-support/dify-support-chat/src/main/java/io/github/guoshiqiufeng/dify/chat/dto/response/AppInfoResponse.java
- dify/dify-support/dify-support-chat/src/main/java/io/github/guoshiqiufeng/dify/chat/dto/response/AppMetaResponse.java
- dify/dify-support/dify-support-chat/src/main/java/io/github/guoshiqiufeng/dify/chat/impl/DifyChatClientImpl.java
- dify/dify-support/dify-support-chat/src/test/java/io/github/guoshiqiufeng/dify/chat/client/DifyChatClientTest.java
- dify/dify-support/dify-support-chat/src/test/java/io/github/guoshiqiufeng/dify/chat/impl/DifyChatClientImplTest.java
- dify/dify-support/dify-support-dataset/src/main/java/io/github/guoshiqiufeng/dify/dataset/constant/DatasetUriConstant.java
- dify/spring-boot-starter/dify-spring-boot-starter/src/test/java/io/github/guoshiqiufeng/dify/boot/ChatTest.java
- dify/spring-boot2-starter/dify-spring-boot2-starter/src/test/java/io/github/guoshiqiufeng/dify/boot/ChatTest.java
- docs/en/guide/feature/chat.md
- docs/guide/feature/chat.md
feat: [chat] meta
Resolves #88 
Resolves #89 
> [!Tip]
>
change.
> feat: [chat] info/meta

- dify/dify-client/dify-client-spring5/src/main/java/io/github/guoshiqiufeng/dify/client/spring5/base/BaseDifyDefaultClient.java
- dify/dify-client/dify-client-spring5/src/test/java/io/github/guoshiqiufeng/dify/client/spring5/BaseClientTest.java
- dify/dify-client/dify-client-spring5/src/test/java/io/github/guoshiqiufeng/dify/client/spring5/base/BaseDifyDefaultClientTest.java
- dify/dify-client/dify-client-spring5/src/test/java/io/github/guoshiqiufeng/dify/client/spring5/chat/DifyChatDefaultClientTest.java
- dify/dify-client/dify-client-spring5/src/test/java/io/github/guoshiqiufeng/dify/client/spring5/dataset/DifyDatasetDefaultClientTest.java
- dify/dify-client/dify-client-spring5/src/test/java/io/github/guoshiqiufeng/dify/client/spring5/server/DifyServerDefaultClientTest.java
- dify/dify-client/dify-client-spring5/src/test/java/io/github/guoshiqiufeng/dify/client/spring5/workflow/DifyWorkflowDefaultClientTest.java
- dify/dify-client/dify-client-spring6/src/test/java/io/github/guoshiqiufeng/dify/client/spring6/BaseClientTest.java
- dify/dify-client/dify-client-spring6/src/test/java/io/github/guoshiqiufeng/dify/client/spring6/chat/DifyChatDefaultClientTest.java
- dify/dify-client/dify-client-spring6/src/test/java/io/github/guoshiqiufeng/dify/client/spring6/dataset/DifyDatasetDefaultClientTest.java
- dify/dify-client/dify-client-spring6/src/test/java/io/github/guoshiqiufeng/dify/client/spring6/server/DifyServerDefaultClientTest.java
- dify/dify-client/dify-client-spring6/src/test/java/io/github/guoshiqiufeng/dify/client/spring6/workflow/DifyWorkflowDefaultClientTest.java
- dify/dify-support/dify-support-chat/src/test/java/io/github/guoshiqiufeng/dify/chat/enums/StreamEventEnumTest.java
- dify/dify-support/dify-support-dataset/src/test/java/io/github/guoshiqiufeng/dify/dataset/enums/IndexingTechniqueEnumTest.java
- dify/dify-support/dify-support-dataset/src/test/java/io/github/guoshiqiufeng/dify/dataset/enums/MetaDataActionEnumTest.java
- dify/dify-support/dify-support-dataset/src/test/java/io/github/guoshiqiufeng/dify/dataset/enums/ModelFeatureEnumTest.java
- dify/dify-support/dify-support-dataset/src/test/java/io/github/guoshiqiufeng/dify/dataset/enums/ModelStatusEnumTest.java
- dify/dify-support/dify-support-dataset/src/test/java/io/github/guoshiqiufeng/dify/dataset/enums/PermissionEnumTest.java
- dify/dify-support/dify-support-dataset/src/test/java/io/github/guoshiqiufeng/dify/dataset/enums/ProviderEnumTest.java
- dify/dify-support/dify-support-dataset/src/test/java/io/github/guoshiqiufeng/dify/dataset/enums/RerankingModeEnumTest.java
- dify/dify-support/dify-support-dataset/src/test/java/io/github/guoshiqiufeng/dify/dataset/enums/SearchMethodEnumTest.java
- dify/dify-support/dify-support-dataset/src/test/java/io/github/guoshiqiufeng/dify/dataset/enums/document/DocFormEnumTest.java
- dify/dify-support/dify-support-dataset/src/test/java/io/github/guoshiqiufeng/dify/dataset/enums/document/DocTypeEnumTest.java
- dify/dify-support/dify-support-dataset/src/test/java/io/github/guoshiqiufeng/dify/dataset/enums/document/ModeEnumTest.java
- dify/dify-support/dify-support-dataset/src/test/java/io/github/guoshiqiufeng/dify/dataset/enums/document/ParentModeEnumTest.java
- dify/dify-support/dify-support-dataset/src/test/java/io/github/guoshiqiufeng/dify/dataset/enums/document/PreProcessingRuleTypeEnumTest.java
- dify/dify-support/dify-support-dataset/src/test/java/io/github/guoshiqiufeng/dify/dataset/impl/DifyDatasetClientImplTest.java
- dify/dify-support/dify-support-server/src/test/java/io/github/guoshiqiufeng/dify/server/client/BaseDifyServerTokenTest.java
- dify/dify-support/dify-support-server/src/test/java/io/github/guoshiqiufeng/dify/server/client/DifyServerTokenDefaultTest.java
- dify/dify-support/dify-support-server/src/test/java/io/github/guoshiqiufeng/dify/server/client/DifyServerTokenRedisTest.java
Resolves #93 
> [!Tip]
>
change.
> feat: test coverage

- .github/workflows/gradle-dify-test.yml
> feat: add codecov/test-results-action

- .github/workflows/gradle-dify-test.yml
- dify/dify-client/dify-client-spring5/src/main/java/io/github/guoshiqiufeng/dify/client/spring5/chat/DifyChatDefaultClient.java
- dify/dify-client/dify-client-spring5/src/test/java/io/github/guoshiqiufeng/dify/client/spring5/BaseClientTest.java
- dify/dify-client/dify-client-spring5/src/test/java/io/github/guoshiqiufeng/dify/client/spring5/chat/DifyChatDefaultClientTest.java
- dify/dify-client/dify-client-spring6/src/main/java/io/github/guoshiqiufeng/dify/client/spring6/chat/DifyChatDefaultClient.java
- dify/dify-client/dify-client-spring6/src/test/java/io/github/guoshiqiufeng/dify/client/spring6/BaseClientTest.java
- dify/dify-client/dify-client-spring6/src/test/java/io/github/guoshiqiufeng/dify/client/spring6/chat/DifyChatDefaultClientTest.java
- dify/dify-core/src/test/java/io/github/guoshiqiufeng/dify/core/client/BaseDifyClientTest.java
- dify/dify-core/src/test/java/io/github/guoshiqiufeng/dify/core/exception/BaseExceptionTest.java
- dify/dify-core/src/test/java/io/github/guoshiqiufeng/dify/core/pojo/response/MessagesResponseVOTest.java
- dify/dify-support/dify-support-chat/src/main/java/io/github/guoshiqiufeng/dify/chat/DifyChat.java
- dify/dify-support/dify-support-chat/src/main/java/io/github/guoshiqiufeng/dify/chat/client/DifyChatClient.java
- dify/dify-support/dify-support-chat/src/main/java/io/github/guoshiqiufeng/dify/chat/dto/request/AppAnnotationCreateRequest.java
- dify/dify-support/dify-support-chat/src/main/java/io/github/guoshiqiufeng/dify/chat/dto/request/AppAnnotationPageRequest.java
- dify/dify-support/dify-support-chat/src/main/java/io/github/guoshiqiufeng/dify/chat/dto/request/AppAnnotationUpdateRequest.java
- dify/dify-support/dify-support-chat/src/main/java/io/github/guoshiqiufeng/dify/chat/dto/response/AppAnnotationDeleteResponse.java
- dify/dify-support/dify-support-chat/src/main/java/io/github/guoshiqiufeng/dify/chat/dto/response/AppAnnotationResponse.java
- dify/dify-support/dify-support-chat/src/main/java/io/github/guoshiqiufeng/dify/chat/impl/DifyChatClientImpl.java
- dify/dify-support/dify-support-chat/src/test/java/io/github/guoshiqiufeng/dify/chat/client/DifyChatClientTest.java
- dify/dify-support/dify-support-chat/src/test/java/io/github/guoshiqiufeng/dify/chat/impl/DifyChatClientImplTest.java
- dify/dify-support/dify-support-dataset/src/main/java/io/github/guoshiqiufeng/dify/dataset/constant/DatasetUriConstant.java
- dify/dify-support/dify-support-dataset/src/test/java/io/github/guoshiqiufeng/dify/dataset/dto/RetrievalModelTest.java
- dify/dify-support/dify-support-dataset/src/test/java/io/github/guoshiqiufeng/dify/dataset/dto/response/SegmentDataTest.java
- dify/dify-support/dify-support-dataset/src/test/java/io/github/guoshiqiufeng/dify/dataset/dto/response/SegmentUpdateResponseTest.java
- dify/spring-boot-starter/dify-spring-boot-starter/src/test/java/io/github/guoshiqiufeng/dify/boot/ChatTest.java
- dify/spring-boot2-starter/dify-spring-boot2-starter/src/test/java/io/github/guoshiqiufeng/dify/boot/ChatTest.java
- docs/en/guide/feature/chat.md
- docs/en/guide/introduction.md
- docs/guide/feature/chat.md
- docs/guide/introduction.md
Resolves #99 
> [!Tip]
>
change.
> feat: app annotations

- .github/.codecov.yml
- dify/dify-support/dify-support-chat/src/main/java/io/github/guoshiqiufeng/dify/chat/dto/response/message/NodeFinishedData.java
- dify/dify-support/dify-support-chat/src/test/java/io/github/guoshiqiufeng/dify/chat/dto/response/message/CompletionDataTest.java
- dify/dify-support/dify-support-chat/src/test/java/io/github/guoshiqiufeng/dify/chat/dto/response/message/NodeFinishedDataTest.java
- dify/dify-support/dify-support-chat/src/test/java/io/github/guoshiqiufeng/dify/chat/dto/response/message/NodeStartedDataTest.java
- dify/dify-support/dify-support-chat/src/test/java/io/github/guoshiqiufeng/dify/chat/dto/response/message/WorkflowFinishedDataTest.java
- dify/dify-support/dify-support-chat/src/test/java/io/github/guoshiqiufeng/dify/chat/dto/response/message/WorkflowStartedDataTest.java
- docs/en/guide/introduction.md
- docs/guide/introduction.md
> feat: test cov

- .github/.codecov.yml
- dify/dify-core/src/main/java/io/github/guoshiqiufeng/dify/core/pojo/request/ChatMessageVO.java
- dify/dify-core/src/test/java/io/github/guoshiqiufeng/dify/core/pojo/request/ChatMessageVOJsonTest.java
- dify/dify-core/src/test/java/io/github/guoshiqiufeng/dify/core/pojo/request/ChatMessageVOTest.java
- dify/dify-support/dify-support-chat/src/test/java/io/github/guoshiqiufeng/dify/chat/dto/response/AppParametersResponseVOJsonTest.java
- dify/dify-support/dify-support-chat/src/test/java/io/github/guoshiqiufeng/dify/chat/dto/response/AppParametersResponseVOTest.java
- dify/dify-support/dify-support-chat/src/test/java/io/github/guoshiqiufeng/dify/chat/dto/response/ChatMessageSendResponseJsonTest.java
- dify/dify-support/dify-support-chat/src/test/java/io/github/guoshiqiufeng/dify/chat/dto/response/ChatMessageSendResponseTest.java
- dify/dify-support/dify-support-dataset/src/test/java/io/github/guoshiqiufeng/dify/dataset/utils/MultipartBodyUtilTest.java
- dify/dify-support/dify-support-server/build.gradle
- dify/dify-support/dify-support-server/src/main/java/io/github/guoshiqiufeng/dify/server/dto/response/AppsResponseVO.java
- dify/dify-support/dify-support-server/src/test/java/io/github/guoshiqiufeng/dify/server/dto/request/DifyLoginRequestVOJsonTest.java
- dify/dify-support/dify-support-server/src/test/java/io/github/guoshiqiufeng/dify/server/dto/request/DifyLoginRequestVOTest.java
- dify/dify-support/dify-support-server/src/test/java/io/github/guoshiqiufeng/dify/server/dto/request/MockServerServiceTest.java
- dify/dify-support/dify-support-server/src/test/java/io/github/guoshiqiufeng/dify/server/dto/response/AppsResponseVOJsonTest.java
- dify/dify-support/dify-support-server/src/test/java/io/github/guoshiqiufeng/dify/server/dto/response/AppsResponseVOTest.java
- dify/dify-support/dify-support-server/src/test/java/io/github/guoshiqiufeng/dify/server/exception/DifyServerExceptionEnumTest.java
- dify/dify-support/dify-support-server/src/test/java/io/github/guoshiqiufeng/dify/server/exception/DifyServerExceptionTest.java
- dify/dify-support/dify-support-server/src/test/java/io/github/guoshiqiufeng/dify/server/exception/ExceptionTestUtil.java
- dify/dify-support/dify-support-workflow/src/main/java/io/github/guoshiqiufeng/dify/workflow/dto/response/stream/NodeFinishedData.java
- dify/dify-support/dify-support-workflow/src/main/java/io/github/guoshiqiufeng/dify/workflow/dto/response/stream/NodeStartedData.java
- dify/dify-support/dify-support-workflow/src/main/java/io/github/guoshiqiufeng/dify/workflow/dto/response/stream/WorkflowFinishedData.java
- dify/dify-support/dify-support-workflow/src/main/java/io/github/guoshiqiufeng/dify/workflow/dto/response/stream/WorkflowStartedData.java
- dify/dify-support/dify-support-workflow/src/test/java/io/github/guoshiqiufeng/dify/workflow/dto/response/WorkflowInfoResponseJsonTest.java
- dify/dify-support/dify-support-workflow/src/test/java/io/github/guoshiqiufeng/dify/workflow/dto/response/WorkflowInfoResponseTest.java
- dify/dify-support/dify-support-workflow/src/test/java/io/github/guoshiqiufeng/dify/workflow/dto/response/jackson/WorkflowRunStreamResponseDeserializerTest.java
- dify/dify-support/dify-support-workflow/src/test/java/io/github/guoshiqiufeng/dify/workflow/dto/response/stream/NodeFinishedDataTest.java
- dify/dify-support/dify-support-workflow/src/test/java/io/github/guoshiqiufeng/dify/workflow/dto/response/stream/NodeStartedDataTest.java
- dify/dify-support/dify-support-workflow/src/test/java/io/github/guoshiqiufeng/dify/workflow/dto/response/stream/WorkflowFinishedDataTest.java
- dify/dify-support/dify-support-workflow/src/test/java/io/github/guoshiqiufeng/dify/workflow/dto/response/stream/WorkflowStartedDataTest.java
> feat: test cov up to 80%

- README-zh.md
- README.md
- dify/dify-client/dify-client-spring5/src/main/java/io/github/guoshiqiufeng/dify/client/spring5/dataset/DifyDatasetDefaultClient.java
- dify/dify-client/dify-client-spring6/src/main/java/io/github/guoshiqiufeng/dify/client/spring6/dataset/DifyDatasetDefaultClient.java
- dify/dify-support/dify-support-dataset/src/main/java/io/github/guoshiqiufeng/dify/dataset/dto/request/SegmentPageRequest.java
- gradle.properties
> fix: segment page param (page\limit)

- dify/dify-client/dify-client-spring6/src/test/java/io/github/guoshiqiufeng/dify/client/spring6/dataset/DifyDatasetDefaultClientTest.java
- dify/dify-support/dify-support-chat/src/main/java/io/github/guoshiqiufeng/dify/chat/dto/response/jackson/CompletionDataDeserializer.java
- dify/dify-support/dify-support-chat/src/test/java/io/github/guoshiqiufeng/dify/chat/dto/response/jackson/CompletionDataDeserializerTest.java
- dify/dify-support/dify-support-workflow/src/main/java/io/github/guoshiqiufeng/dify/workflow/dto/response/MetaData.java
- dify/dify-support/dify-support-workflow/src/main/java/io/github/guoshiqiufeng/dify/workflow/dto/response/jackson/WorkflowRunStreamResponseDeserializer.java
- dify/dify-support/dify-support-workflow/src/main/java/io/github/guoshiqiufeng/dify/workflow/dto/response/stream/AgentLogData.java
- dify/dify-support/dify-support-workflow/src/main/java/io/github/guoshiqiufeng/dify/workflow/dto/response/stream/ParallelBranchFinishedData.java
- dify/dify-support/dify-support-workflow/src/main/java/io/github/guoshiqiufeng/dify/workflow/dto/response/stream/ParallelBranchStartedData.java
- dify/dify-support/dify-support-workflow/src/main/java/io/github/guoshiqiufeng/dify/workflow/enums/StreamEventEnum.java
- dify/dify-support/dify-support-workflow/src/test/java/io/github/guoshiqiufeng/dify/workflow/dto/response/jackson/WorkflowRunStreamResponseDeserializerTest.java
Fixes #131 
> [!Tip]
>
change.
> fix: streamevent data

- README-zh.md
- README.md
- dify/dify-core/src/main/java/io/github/guoshiqiufeng/dify/core/pojo/request/ChatMessageVO.java
- dify/dify-support/dify-support-chat/src/main/java/io/github/guoshiqiufeng/dify/chat/dto/request/ChatMessageSendRequest.java
- dify/dify-support/dify-support-workflow/src/main/java/io/github/guoshiqiufeng/dify/workflow/dto/request/WorkflowRunRequest.java
- gradle.properties
> fix: chat/workflow file add uploadFileId

- dify/dify-client/dify-client-spring5/src/main/java/io/github/guoshiqiufeng/dify/client/spring5/utils/WebClientUtil.java
- dify/dify-client/dify-client-spring5/src/test/java/io/github/guoshiqiufeng/dify/client/spring5/utils/WebClientUtilTest.java
- dify/dify-client/dify-client-spring6/src/main/java/io/github/guoshiqiufeng/dify/client/spring6/base/BaseDifyDefaultClient.java
- dify/dify-client/dify-client-spring6/src/main/java/io/github/guoshiqiufeng/dify/client/spring6/utils/WebClientUtil.java
- dify/dify-client/dify-client-spring6/src/test/java/io/github/guoshiqiufeng/dify/client/spring6/base/BaseDifyDefaultClientTest.java
- dify/dify-client/dify-client-spring6/src/test/java/io/github/guoshiqiufeng/dify/client/spring6/dataset/DifyDatasetDefaultClientTest.java
- dify/dify-client/dify-client-spring6/src/test/java/io/github/guoshiqiufeng/dify/client/spring6/utils/WebClientUtilTest.java
- dify/dify-core/src/main/java/io/github/guoshiqiufeng/dify/core/exception/BaseException.java
- dify/dify-core/src/main/java/io/github/guoshiqiufeng/dify/core/exception/DiftClientExceptionEnum.java
- dify/dify-core/src/main/java/io/github/guoshiqiufeng/dify/core/exception/DifyClientException.java
- dify/dify-core/src/test/java/io/github/guoshiqiufeng/dify/core/exception/BaseExceptionTest.java
- dify/dify-core/src/test/java/io/github/guoshiqiufeng/dify/core/exception/DifyClientExceptionTest.java
- dify/dify-support/dify-support-dataset/src/main/java/io/github/guoshiqiufeng/dify/dataset/dto/request/DatasetCreateRequest.java
- dify/dify-support/dify-support-dataset/src/main/java/io/github/guoshiqiufeng/dify/dataset/dto/response/DatasetInfoResponse.java
- dify/dify-support/dify-support-dataset/src/main/java/io/github/guoshiqiufeng/dify/dataset/dto/response/DatasetResponse.java
- dify/dify-support/dify-support-workflow/src/main/java/io/github/guoshiqiufeng/dify/workflow/dto/response/MetaData.java
- dify/dify-support/dify-support-workflow/src/main/java/io/github/guoshiqiufeng/dify/workflow/dto/response/stream/AgentLogData.java
- dify/dify-support/dify-support-workflow/src/main/java/io/github/guoshiqiufeng/dify/workflow/dto/response/stream/ParallelBranchFinishedData.java
- dify/dify-support/dify-support-workflow/src/main/java/io/github/guoshiqiufeng/dify/workflow/dto/response/stream/ParallelBranchStartedData.java
- docs/en/guide/feature/dataset.md
- docs/guide/feature/dataset.md
- gradle.properties
Resolves #135 
> [!Tip]
>
change.
> feat: exception refinement

- dify/dify-client/dify-client-spring6/src/main/java/io/github/guoshiqiufeng/dify/client/spring6/utils/DifyMessageConverters.java
- dify/dify-client/dify-client-spring6/src/test/java/io/github/guoshiqiufeng/dify/client/spring6/utils/DifyMessageConvertersTest.java
Fixes #137
Fixes #138 
> [!Tip]
>
change.
> fix: jackson configuration affected under springboot3

- dify/dify-client/dify-client-spring5/src/main/java/io/github/guoshiqiufeng/dify/client/spring5/chat/DifyChatDefaultClient.java
- dify/dify-client/dify-client-spring5/src/test/java/io/github/guoshiqiufeng/dify/client/spring5/chat/DifyChatDefaultClientTest.java
Fixes #141 
> [!Tip]
>
change.
> fix:  stopMessagesStream、deleteConversation on springboot2

- dify/dify-client/dify-client-spring5/src/main/java/io/github/guoshiqiufeng/dify/client/spring5/chat/DifyChatDefaultClient.java
- dify/dify-client/dify-client-spring5/src/main/java/io/github/guoshiqiufeng/dify/client/spring5/dataset/DifyDatasetDefaultClient.java
- dify/dify-client/dify-client-spring5/src/test/java/io/github/guoshiqiufeng/dify/client/spring5/chat/DifyChatDefaultClientTest.java
- dify/dify-client/dify-client-spring5/src/test/java/io/github/guoshiqiufeng/dify/client/spring5/dataset/DifyDatasetDefaultClientTest.java
fix: deleteDocument、deleteSegment、deleteSegmentChildChunk on springboot2
> [!Tip]
>
change.
> fix:  deleteAppAnnotation 、deleteDocument、deleteSegment、deleteSegmentChildChunk on springboot2

- dify/dify-client/dify-client-spring6/src/test/java/io/github/guoshiqiufeng/dify/client/spring6/workflow/DifyWorkflowDefaultClientTest.java
- dify/dify-support/dify-support-chat/src/main/java/io/github/guoshiqiufeng/dify/chat/dto/response/jackson/CompletionDataDeserializer.java
- dify/dify-support/dify-support-workflow/src/main/java/io/github/guoshiqiufeng/dify/workflow/dto/response/jackson/WorkflowRunStreamResponseDeserializer.java
- dify/dify-support/dify-support-workflow/src/test/java/io/github/guoshiqiufeng/dify/workflow/dto/response/jackson/WorkflowRunStreamResponseDeserializerTest.java
Fixes #146 
> [!Tip]
>
change.
> fix: Local Configuration Affects StreamResponse

- dify/dify-support/dify-support-chat/src/main/java/io/github/guoshiqiufeng/dify/chat/dto/response/jackson/CompletionDataDeserializer.java
- dify/dify-support/dify-support-workflow/src/main/java/io/github/guoshiqiufeng/dify/workflow/dto/response/jackson/WorkflowRunStreamResponseDeserializer.java
- dify/dify-support/dify-support-workflow/src/main/java/io/github/guoshiqiufeng/dify/workflow/dto/response/stream/WorkflowStartedData.java
- gradle.properties
Fixes #149 
> [!Tip]
>
change.
> fix: DataDeserializer ignore unknown fields

- .github/workflows/gradle-dify-test.yml
- dify/dify-support/dify-support-chat/src/main/java/io/github/guoshiqiufeng/dify/chat/dto/response/MetaData.java
- dify/dify-support/dify-support-chat/src/main/java/io/github/guoshiqiufeng/dify/chat/dto/response/jackson/ChatMessageSendCompletionResponseDeserializer.java
- dify/dify-support/dify-support-chat/src/main/java/io/github/guoshiqiufeng/dify/chat/dto/response/jackson/CompletionDataDeserializer.java
- dify/dify-support/dify-support-chat/src/main/java/io/github/guoshiqiufeng/dify/chat/dto/response/message/AgentLogData.java
- dify/dify-support/dify-support-chat/src/main/java/io/github/guoshiqiufeng/dify/chat/dto/response/message/EmptyData.java
- dify/dify-support/dify-support-chat/src/main/java/io/github/guoshiqiufeng/dify/chat/dto/response/message/ParallelBranchFinishedData.java
- dify/dify-support/dify-support-chat/src/main/java/io/github/guoshiqiufeng/dify/chat/dto/response/message/ParallelBranchStartedData.java
- dify/dify-support/dify-support-chat/src/main/java/io/github/guoshiqiufeng/dify/chat/dto/response/message/WorkflowFinishedData.java
- dify/dify-support/dify-support-chat/src/main/java/io/github/guoshiqiufeng/dify/chat/enums/StreamEventEnum.java
- dify/dify-support/dify-support-chat/src/test/java/io/github/guoshiqiufeng/dify/chat/dto/response/jackson/ChatMessageSendCompletionResponseDeserializerTest.java
- dify/dify-support/dify-support-chat/src/test/java/io/github/guoshiqiufeng/dify/chat/enums/StreamEventEnumTest.java
- dify/dify-support/dify-support-workflow/src/main/java/io/github/guoshiqiufeng/dify/workflow/dto/response/jackson/WorkflowRunStreamResponseDeserializer.java
- gradle.properties
Fixes #151 
> [!Tip]
>
change.
> fix: completion Deserializer

- .github/ISSUE_TEMPLATE/bug_report.yml
- dify/dify-client/dify-client-spring5/src/main/java/io/github/guoshiqiufeng/dify/client/spring5/utils/DatasetHeaderUtils.java
- dify/dify-client/dify-client-spring5/src/main/java/io/github/guoshiqiufeng/dify/client/spring5/utils/DifyExchangeStrategies.java
- dify/dify-client/dify-client-spring6/src/main/java/io/github/guoshiqiufeng/dify/client/spring6/utils/DatasetHeaderUtils.java
- dify/dify-client/dify-client-spring6/src/main/java/io/github/guoshiqiufeng/dify/client/spring6/utils/DifyExchangeStrategies.java
- dify/dify-client/dify-client-spring6/src/main/java/io/github/guoshiqiufeng/dify/client/spring6/utils/DifyMessageConverters.java
- dify/dify-support/dify-support-chat/src/main/java/io/github/guoshiqiufeng/dify/chat/dto/response/jackson/ChatMessageSendCompletionResponseDeserializer.java
- dify/dify-support/dify-support-chat/src/main/java/io/github/guoshiqiufeng/dify/chat/dto/response/jackson/CompletionDataDeserializer.java
- dify/dify-support/dify-support-chat/src/main/java/io/github/guoshiqiufeng/dify/chat/dto/response/message/AgentLogData.java
- dify/dify-support/dify-support-chat/src/main/java/io/github/guoshiqiufeng/dify/chat/dto/response/message/EmptyData.java
- dify/dify-support/dify-support-chat/src/main/java/io/github/guoshiqiufeng/dify/chat/dto/response/message/ParallelBranchStartedData.java
- dify/dify-support/dify-support-chat/src/test/java/io/github/guoshiqiufeng/dify/chat/dto/response/jackson/ChatMessageSendCompletionResponseDeserializerTest.java
> format code

- dify/dify-core/src/main/java/io/github/guoshiqiufeng/dify/core/enums/message/MessageFileTransferMethodEnum.java
- dify/dify-core/src/main/java/io/github/guoshiqiufeng/dify/core/enums/message/MessageFileTypeEnum.java
- dify/dify-core/src/test/java/io/github/guoshiqiufeng/dify/core/enums/message/MessageFileTransferMethodEnumTest.java
- dify/dify-core/src/test/java/io/github/guoshiqiufeng/dify/core/enums/message/MessageFileTypeEnumTest.java
- dify/dify-support/dify-support-chat/src/main/java/io/github/guoshiqiufeng/dify/chat/dto/request/ChatMessageSendRequest.java
- dify/dify-support/dify-support-chat/src/test/java/io/github/guoshiqiufeng/dify/chat/dto/request/ChatMessageFileTest.java
- dify/dify-support/dify-support-workflow/src/main/java/io/github/guoshiqiufeng/dify/workflow/dto/request/WorkflowRunRequest.java
- dify/dify-support/dify-support-workflow/src/test/java/io/github/guoshiqiufeng/dify/workflow/dto/request/WorkflowFileTest.java
- gradle.properties
> feat: Add MessageFileTypeEnum, MessageFileTransferMethodEnum for ChatMessageFile and WorkflowFile.

- dify/dify-client/dify-client-spring6/build.gradle
- dify/spring-boot-starter/dify-spring-boot-starter-autoconfigure/build.gradle
- dify/spring-boot-starter/dify-spring-boot-starter/build.gradle
- ext.gradle
> dependency: update springboot3 to 3.5.0

- dify/dify-support/dify-support-server/src/main/java/io/github/guoshiqiufeng/dify/server/dto/response/AppsResponse.java
- dify/dify-support/dify-support-server/src/test/java/io/github/guoshiqiufeng/dify/server/dto/response/AppsResponseTest.java
- gradle.properties
Fixes #165 
> [!Tip]
>
change.
> fix: server apps tags type error

- dify/dify-client/dify-client-spring6/src/main/java/io/github/guoshiqiufeng/dify/client/spring6/chat/DifyChatDefaultClient.java
- dify/dify-client/dify-client-spring6/src/main/java/io/github/guoshiqiufeng/dify/client/spring6/dataset/DifyDatasetDefaultClient.java
- gradle.properties
> Fix delete

- dify/dify-support/dify-support-chat/src/main/java/io/github/guoshiqiufeng/dify/chat/enums/StreamEventEnum.java
- dify/dify-support/dify-support-chat/src/test/java/io/github/guoshiqiufeng/dify/chat/enums/StreamEventEnumTest.java
- gradle.properties
Resolves #171 
> [!Tip]
>
change.
> StreamEventEnum add message_end

- dify/dify-client/dify-client-spring6/src/main/java/io/github/guoshiqiufeng/dify/client/spring6/utils/DifyMessageConverters.java
- dify/dify-client/dify-client-spring6/src/test/java/io/github/guoshiqiufeng/dify/client/spring6/utils/DifyMessageConvertersTest.java
Fixes #168 
Fixes #174 
> [!Tip]
>
change.
> fix: jackson config

- dify/dify-support/dify-support-chat/src/main/java/io/github/guoshiqiufeng/dify/chat/dto/response/ChatMessageSendCompletionResponse.java
- gradle.properties
Fixes #184 
> [!Tip]
>
change.
> fix: agent_thought return

- dify/dify-client/dify-client-spring5/src/main/java/io/github/guoshiqiufeng/dify/client/spring5/builder/DifyDatasetBuilder.java
- dify/dify-client/dify-client-spring5/src/test/java/io/github/guoshiqiufeng/dify/client/spring5/builder/DifyDatasetBuilderTest.java
- dify/dify-client/dify-client-spring6/src/main/java/io/github/guoshiqiufeng/dify/client/spring6/builder/DifyDatasetBuilder.java
- dify/dify-client/dify-client-spring6/src/test/java/io/github/guoshiqiufeng/dify/client/spring6/builder/DifyDatasetBuilderTest.java
- docs/en/guide/builder.md
- docs/guide/builder.md
Resolves #186 
> [!Tip]
>
change.
> feat: DifyDatasetBuilder expand apikey

- dify/dify-client/dify-client-spring5/src/main/java/io/github/guoshiqiufeng/dify/client/spring5/dataset/DifyDatasetDefaultClient.java
- dify/dify-client/dify-client-spring6/src/main/java/io/github/guoshiqiufeng/dify/client/spring6/dataset/DifyDatasetDefaultClient.java
- dify/dify-support/dify-support-dataset/src/main/java/io/github/guoshiqiufeng/dify/dataset/DifyDataset.java
- dify/dify-support/dify-support-dataset/src/main/java/io/github/guoshiqiufeng/dify/dataset/client/DifyDatasetClient.java
- dify/dify-support/dify-support-dataset/src/main/java/io/github/guoshiqiufeng/dify/dataset/constant/DatasetUriConstant.java
- dify/dify-support/dify-support-dataset/src/main/java/io/github/guoshiqiufeng/dify/dataset/dto/response/DatasetStatusResponse.java
- dify/dify-support/dify-support-dataset/src/main/java/io/github/guoshiqiufeng/dify/dataset/enums/document/DocActionEnum.java
- dify/dify-support/dify-support-dataset/src/main/java/io/github/guoshiqiufeng/dify/dataset/impl/DifyDatasetClientImpl.java
- dify/dify-support/dify-support-dataset/src/test/java/io/github/guoshiqiufeng/dify/dataset/impl/DifyDatasetClientImplTest.java
> feat: Dataset support Update Document Status

- dify/dify-client/dify-client-spring5/src/main/java/io/github/guoshiqiufeng/dify/client/spring5/builder/DifyDatasetBuilder.java
- dify/dify-client/dify-client-spring5/src/main/java/io/github/guoshiqiufeng/dify/client/spring5/dataset/DifyDatasetDefaultClient.java
- dify/dify-client/dify-client-spring5/src/test/java/io/github/guoshiqiufeng/dify/client/spring5/dataset/DifyDatasetDefaultClientTest.java
- dify/dify-client/dify-client-spring6/src/main/java/io/github/guoshiqiufeng/dify/client/spring6/builder/DifyDatasetBuilder.java
- dify/dify-client/dify-client-spring6/src/main/java/io/github/guoshiqiufeng/dify/client/spring6/dataset/DifyDatasetDefaultClient.java
- dify/dify-client/dify-client-spring6/src/test/java/io/github/guoshiqiufeng/dify/client/spring6/builder/DifyDatasetBuilderTest.java
- dify/dify-client/dify-client-spring6/src/test/java/io/github/guoshiqiufeng/dify/client/spring6/dataset/DifyDatasetDefaultClientTest.java
- dify/dify-support/dify-support-dataset/src/main/java/io/github/guoshiqiufeng/dify/dataset/DifyDataset.java
- dify/dify-support/dify-support-dataset/src/main/java/io/github/guoshiqiufeng/dify/dataset/client/DifyDatasetClient.java
- dify/dify-support/dify-support-dataset/src/main/java/io/github/guoshiqiufeng/dify/dataset/dto/response/DatasetStatusResponse.java
- dify/dify-support/dify-support-dataset/src/main/java/io/github/guoshiqiufeng/dify/dataset/impl/DifyDatasetClientImpl.java
- dify/dify-support/dify-support-dataset/src/test/java/io/github/guoshiqiufeng/dify/dataset/impl/DifyDatasetClientImplTest.java
- dify/spring-boot-starter/dify-spring-boot-starter/src/test/java/io/github/guoshiqiufeng/dify/boot/DatasetTest.java
- dify/spring-boot2-starter/dify-spring-boot2-starter/src/test/java/io/github/guoshiqiufeng/dify/boot/DatasetTest.java
- docs/en/guide/feature/chat.md
- docs/en/guide/feature/dataset.md
- docs/guide/builder.md
- docs/guide/feature/chat.md
- docs/guide/feature/dataset.md
> feat: change document status

- dify/dify-support/dify-support-chat/src/main/java/io/github/guoshiqiufeng/dify/chat/dto/response/ChatMessageSendCompletionResponse.java
- dify/dify-support/dify-support-chat/src/main/java/io/github/guoshiqiufeng/dify/chat/dto/response/jackson/ChatMessageSendCompletionResponseDeserializer.java
- dify/dify-support/dify-support-chat/src/main/java/io/github/guoshiqiufeng/dify/chat/enums/StreamEventEnum.java
- dify/dify-support/dify-support-chat/src/test/java/io/github/guoshiqiufeng/dify/chat/dto/response/jackson/ChatMessageSendCompletionResponseDeserializerTest.java
- dify/dify-support/dify-support-chat/src/test/java/io/github/guoshiqiufeng/dify/chat/enums/StreamEventEnumTest.java
> expand event: error、ping

- ext.gradle
> dependency: update springboot3 to 3.5.5

- dify/dify-core/src/main/java/io/github/guoshiqiufeng/dify/core/pipeline/PipelineContext.java
- dify/dify-core/src/main/java/io/github/guoshiqiufeng/dify/core/pipeline/PipelineHandler.java
- dify/dify-core/src/main/java/io/github/guoshiqiufeng/dify/core/pipeline/PipelineModel.java
- dify/dify-core/src/main/java/io/github/guoshiqiufeng/dify/core/pipeline/PipelineProcess.java
- dify/dify-core/src/main/java/io/github/guoshiqiufeng/dify/core/pipeline/PipelineTemplate.java
- dify/dify-core/src/test/java/io/github/guoshiqiufeng/dify/core/pipeline/PipelineContextTest.java
- dify/dify-core/src/test/java/io/github/guoshiqiufeng/dify/core/pipeline/PipelineHandlerTest.java
- dify/dify-core/src/test/java/io/github/guoshiqiufeng/dify/core/pipeline/PipelineModelTest.java
- dify/dify-core/src/test/java/io/github/guoshiqiufeng/dify/core/pipeline/PipelineProcessTest.java
- dify/dify-core/src/test/java/io/github/guoshiqiufeng/dify/core/pipeline/PipelineTemplateTest.java
- dify/dify-core/src/test/java/io/github/guoshiqiufeng/dify/core/pipeline/TestPipelineModel.java
- dify/dify-core/src/test/java/io/github/guoshiqiufeng/dify/core/pipeline/TestPipelineProcess.java
- dify/dify-support/dify-support-chat/build.gradle
- dify/dify-support/dify-support-chat/src/main/java/io/github/guoshiqiufeng/dify/chat/impl/DifyChatClientImpl.java
- dify/dify-support/dify-support-chat/src/main/java/io/github/guoshiqiufeng/dify/chat/pipeline/ChatMessagePipelineModel.java
- dify/dify-support/dify-support-chat/src/main/java/io/github/guoshiqiufeng/dify/chat/pipeline/DifyChatPipelineUtils.java
- dify/dify-support/dify-support-chat/src/test/java/io/github/guoshiqiufeng/dify/chat/pipeline/ChatMessagePipelineModelTest.java
- dify/dify-support/dify-support-chat/src/test/java/io/github/guoshiqiufeng/dify/chat/pipeline/DifyChatPipelineUtilsTest.java
- dify/dify-support/dify-support-workflow/src/main/java/io/github/guoshiqiufeng/dify/workflow/dto/response/stream/EmptyData.java
- dify/spring-boot-starter/dify-spring-boot-starter-autoconfigure/src/main/java/io/github/guoshiqiufeng/dify/springboot/autoconfigure/DifyChatAutoConfiguration.java
- dify/spring-boot2-starter/dify-spring-boot2-starter-autoconfigure/src/main/java/io/github/guoshiqiufeng/dify/springboot2/autoconfigure/DifyChatAutoConfiguration.java
- docs/en/guide/event/chat.md
- docs/en/guide/event/introduction.md
- docs/en/guide/feature/dataset.md
- docs/guide/event/chat.md
- docs/guide/event/introduction.md
- docs/guide/feature/dataset.md
- ext.gradle
Resolves #193
> [!Tip]
>
change.
> feat: chat message event

- .github/workflows/gradle-dify-test.yml
> update dify test

- dify/dify-client/dify-client-spring5/src/main/java/io/github/guoshiqiufeng/dify/client/spring5/chat/DifyChatDefaultClient.java
- dify/dify-client/dify-client-spring5/src/test/java/io/github/guoshiqiufeng/dify/client/spring5/chat/DifyChatDefaultClientTest.java
- dify/dify-client/dify-client-spring6/src/main/java/io/github/guoshiqiufeng/dify/client/spring6/chat/DifyChatDefaultClient.java
- dify/dify-client/dify-client-spring6/src/test/java/io/github/guoshiqiufeng/dify/client/spring6/chat/DifyChatDefaultClientTest.java
- dify/dify-support/dify-support-chat/src/main/java/io/github/guoshiqiufeng/dify/chat/DifyChat.java
- dify/dify-support/dify-support-chat/src/main/java/io/github/guoshiqiufeng/dify/chat/client/DifyChatClient.java
- dify/dify-support/dify-support-chat/src/main/java/io/github/guoshiqiufeng/dify/chat/constant/ChatUriConstant.java
- dify/dify-support/dify-support-chat/src/main/java/io/github/guoshiqiufeng/dify/chat/dto/request/ConversationVariableRequest.java
- dify/dify-support/dify-support-chat/src/main/java/io/github/guoshiqiufeng/dify/chat/dto/request/UpdateConversationVariableRequest.java
- dify/dify-support/dify-support-chat/src/main/java/io/github/guoshiqiufeng/dify/chat/dto/response/ConversationVariableResponse.java
- dify/dify-support/dify-support-chat/src/main/java/io/github/guoshiqiufeng/dify/chat/impl/DifyChatClientImpl.java
- dify/dify-support/dify-support-chat/src/test/java/io/github/guoshiqiufeng/dify/chat/client/DifyChatClientTest.java
- dify/dify-support/dify-support-chat/src/test/java/io/github/guoshiqiufeng/dify/chat/impl/DifyChatClientImplTest.java
- dify/spring-boot-starter/dify-spring-boot-starter/src/test/java/io/github/guoshiqiufeng/dify/boot/ChatTest.java
- dify/spring-boot2-starter/dify-spring-boot2-starter/src/test/java/io/github/guoshiqiufeng/dify/boot/ChatTest.java
- docs/en/guide/feature/chat.md
- docs/guide/feature/chat.md
> feat: support chat variables

- dify/dify-support/dify-support-dataset/src/main/java/io/github/guoshiqiufeng/dify/dataset/dto/RetrievalModel.java
Fixes #201 
> [!Tip]
>
change.
> fix: RetrievalModel FilteringConditions Condition add filed value
